/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.systemforreform.vista.products;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.systemforreform.controller.ControllerProducto;
import com.mycompany.systemforreform.models.ProductosModel;
import com.mycompany.systemforreform.table.TableDesing;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author thevoid
 */
public class ProductsPanel extends javax.swing.JPanel {

    private DefaultTableModel model;
    private ControllerProducto producto = new ControllerProducto();
    private JPopupMenu menu = new JPopupMenu();

    public ProductsPanel() {
        initComponents();
        visibleProductos();
        mostrarProductos();
        OpcionesMenu();
        mostrarValor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelRound5 = new com.mycompany.systemforreform.vista.PanelRound();
        valorTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        valorInventario = new javax.swing.JLabel();
        panelRound6 = new com.mycompany.systemforreform.vista.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gananciasT = new javax.swing.JLabel();
        panelRound7 = new com.mycompany.systemforreform.vista.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        agotados = new javax.swing.JLabel();
        panelRound8 = new com.mycompany.systemforreform.vista.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalP = new javax.swing.JLabel();
        panelRound1 = new com.mycompany.systemforreform.vista.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new FlatSVGIcon("product/boxP.svg"));
        jLabel1.setText("Administración de Productos");

        jTextField1.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new FlatSVGIcon("product/list.svg"));
        jLabel2.setText("Lista de Productos ");

        jButton1.setBackground(new java.awt.Color(237, 86, 6));
        jButton1.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new FlatSVGIcon("product/add.svg"));
        jButton1.setText("Nuevo Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelRound5.setBackground(new java.awt.Color(51, 51, 51));
        panelRound5.setRoundBottomLeft(20);
        panelRound5.setRoundBottomRight(20);
        panelRound5.setRoundTopLeft(20);
        panelRound5.setRoundTopRight(20);

        valorTotal.setIcon(new FlatSVGIcon("proveedor/money.svg"));
        valorTotal.setText("jLabel3");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor Inventario ");

        valorInventario.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 24)); // NOI18N
        valorInventario.setText("1");

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(3, 3, 3)
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        panelRound6.setBackground(new java.awt.Color(51, 51, 51));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);

        jLabel3.setIcon(new FlatSVGIcon("proveedor/graph.svg"));
        jLabel3.setText("jLabel3");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ganancias Totales");

        gananciasT.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 24)); // NOI18N
        gananciasT.setText("1");

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addComponent(gananciasT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(panelRound6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(142, Short.MAX_VALUE))))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gananciasT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        panelRound7.setBackground(new java.awt.Color(51, 51, 51));
        panelRound7.setRoundBottomLeft(20);
        panelRound7.setRoundBottomRight(20);
        panelRound7.setRoundTopLeft(20);
        panelRound7.setRoundTopRight(20);

        jLabel4.setIcon(new FlatSVGIcon("proveedor/warning.svg"));
        jLabel4.setText("jLabel3");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Productos Agotados ");

        agotados.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 24)); // NOI18N
        agotados.setText("1");

        javax.swing.GroupLayout panelRound7Layout = new javax.swing.GroupLayout(panelRound7);
        panelRound7.setLayout(panelRound7Layout);
        panelRound7Layout.setHorizontalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addComponent(agotados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(panelRound7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(116, Short.MAX_VALUE))))
        );
        panelRound7Layout.setVerticalGroup(
            panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(3, 3, 3)
                .addGroup(panelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agotados, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        panelRound8.setBackground(new java.awt.Color(51, 51, 51));
        panelRound8.setRoundBottomLeft(20);
        panelRound8.setRoundBottomRight(20);
        panelRound8.setRoundTopLeft(20);
        panelRound8.setRoundTopRight(20);

        jLabel6.setIcon(new FlatSVGIcon("proveedor/boxV.svg"));
        jLabel6.setText("jLabel3");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Productos  ");

        totalP.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 24)); // NOI18N
        totalP.setText("1");

        javax.swing.GroupLayout panelRound8Layout = new javax.swing.GroupLayout(panelRound8);
        panelRound8.setLayout(panelRound8Layout);
        panelRound8Layout.setHorizontalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound8Layout.createSequentialGroup()
                        .addComponent(totalP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(panelRound8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(134, Short.MAX_VALUE))))
        );
        panelRound8Layout.setVerticalGroup(
            panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addGroup(panelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalP, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelRound1.setBackground(new java.awt.Color(51, 51, 51));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1)
                .addGap(15, 15, 15))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jLabel15.setIcon(new FlatSVGIcon("product/search.svg"));
        jLabel15.setText("jLabel15");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(237, 86, 6));
        jButton2.setText("Actualizar Datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 655, Short.MAX_VALUE)
                                .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelRound5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRound7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRound6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        visbleProduct();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateComponents(jTable1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void visbleProduct() {
        AddProducts ap = new AddProducts();
        ap.setVisible(true);
        ap.setLocationRelativeTo(null);
    }

    private void OpcionesMenu() {

        JMenuItem item1 = new JMenuItem("Editar");
        JMenuItem item2 = new JMenuItem("Eliminar");
        JMenuItem item3 = new JMenuItem("Detalles");

        menu.add(item1);
        menu.addSeparator();
        menu.add(item2);
        menu.addSeparator();
        menu.add(item3);

        jTable1.setComponentPopupMenu(menu);

        item1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (obtenerFila() == -1) {
                    JOptionPane.showMessageDialog(null, "Selecciones una fila a eliminar", "Error", JOptionPane.ERROR_MESSAGE);
                }
                mostrarDatosEditar();

            }
        });

        item2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                elminarProdcuto();
            }
        });

        item3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 if (obtenerFila() == -1) {
                    JOptionPane.showMessageDialog(null, "Selecciones una fila a eliminar", "Error", JOptionPane.ERROR_MESSAGE);
                }
                 mostrarDatosVista();
            }
        });

    }

    //Estructura tabla productos
    private String[] columnasProdcutos() {
        String[] productos = {
            "Nombre", "ID_Prodcuto",
            "Descripción", "Categorías",
            "Proveedor", "Precio Compra",
            "Precio Venta", "Ganancias",
            "Margen", "Stock Incial", "Stock Min", "Total",
            "Unidad"
        };

        return productos;
    }

    private Class[] clasesP() {
        Class[] produc = {
            java.lang.String.class,
            java.lang.Integer.class,
            java.lang.String.class,
            java.lang.String.class,
            java.lang.String.class,
            java.lang.Double.class,
            java.lang.Double.class,
            java.lang.Double.class,
            java.lang.Double.class,
            java.lang.Integer.class,
            java.lang.Integer.class,
            java.lang.Double.class,
            java.lang.String.class
        };
        return produc;
    }

    private boolean[] editables() {
        boolean[] productEdit = {false, false, false,
            false, false, false,
            false, false, false,
            false, false, false, false};
        return productEdit;
    }

    private void visibleProductos() {
        TableDesing productos = new TableDesing(model, jTable1, columnasProdcutos(), clasesP(), editables());
        productos.creationTable();
    }
    //--------------------------------------------------------------

    private double valorTotalStock() {
        double sumaTotal = 0;
        double total = 0;
        for (Document doc : producto.findAll().find()) {
            sumaTotal += doc.getDouble("precioCompra") * doc.getInteger("stockInicial");

        }
        return Math.round(sumaTotal);
    }

    private double valorGananciasTotales() {
        double sumaTotal = 0;
        for (Document doc : producto.findAll().find()) {
            sumaTotal += doc.getDouble("ganancias") * doc.getInteger("stockInicial");
        }
        return Math.round(sumaTotal);
    }
    
    private int stockAgotado(){
    int cant = 0;
        for (Document doc : producto.findAll().find()) {
           if(doc.getInteger("stockInicial")<=5){
               cant++;
           }
        }
        return cant;
    }

    private int totalProductos() {
        int cant = 0;
        for (Document doc : producto.findAll().find()) {
            cant += doc.getInteger("stockInicial");
        }
        return cant;
    }

    private void mostrarValor() {
        valorInventario.setText(String.valueOf(valorTotalStock()));
        gananciasT.setText(String.valueOf(valorGananciasTotales()));
        totalP.setText(String.valueOf(totalProductos()));
        agotados.setText(String.valueOf(stockAgotado()));
    }

    private void mostrarProductos() {
        model = (DefaultTableModel) jTable1.getModel();

        for (Document document : producto.findAll().find()) {
            model.addRow(new Object[]{
                document.getString("nombre"),
                document.getString("idProductos"),
                document.getString("descripcion"),
                document.getString("categoria"),
                document.getString("proveedor"),
                document.getDouble("precioCompra"),
                document.getDouble("precioVenta"),
                document.getDouble("ganancias"),
                document.getDouble("margenBruto"),
                document.getInteger("stockInicial"),
                document.getInteger("stockMinimo"),
                (document.getDouble("precioCompra") * document.getInteger("stockInicial")),
                document.getString("unidad")

            });
        }
    }

    private void elminarProdcuto() {
        if (obtenerFila() == -1) {
            JOptionPane.showMessageDialog(null, "Selecciones una fila a eliminar", "Error", JOptionPane.ERROR_MESSAGE);
        }
        String eliminar = jTable1.getValueAt(obtenerFila(), 0).toString();
        model.removeRow(obtenerFila());
        producto.deleteByName(eliminar);
    }

    private int obtenerFila() {
        return jTable1.getSelectedRow();
    }

    private ProductosModel producto(String nombre, String id, String descripcion, String categoria,
            String proveedor, double precioC,
            double precioV,
            double ganancias,
            double margen,
            int stock,
            int stockM, String unidad) {

        return new ProductosModel(nombre, id, descripcion, categoria, proveedor, precioC, precioV, ganancias, margen, stock, stockM, unidad);
    }

    private void mostrarDatosEditar() {
        if (obtenerFila() == -1) {

        } else {
            EditarProdcuto ep = new EditarProdcuto(producto(jTable1.getValueAt(obtenerFila(), 0).toString(),
                    jTable1.getValueAt(obtenerFila(), 1).toString(),
                    jTable1.getValueAt(obtenerFila(), 2).toString(),
                    jTable1.getValueAt(obtenerFila(), 3).toString(),
                    jTable1.getValueAt(obtenerFila(), 4).toString(),
                    Double.parseDouble(jTable1.getValueAt(obtenerFila(), 5).toString()),
                    Double.parseDouble(jTable1.getValueAt(obtenerFila(), 6).toString()),
                    Double.parseDouble(jTable1.getValueAt(obtenerFila(), 7).toString()),
                    Double.parseDouble(jTable1.getValueAt(obtenerFila(), 8).toString()),
                    Integer.parseInt(jTable1.getValueAt(obtenerFila(), 9).toString()),
                    Integer.parseInt(jTable1.getValueAt(obtenerFila(), 10).toString()),
                    jTable1.getValueAt(obtenerFila(), 12).toString()));
            
            ep.setVisible(true);
            ep.setLocationRelativeTo(null);
        }

    }
    
     private void mostrarDatosVista() {
        if (obtenerFila() == -1) {

        } else {
            VistaProducto ep = new VistaProducto(producto(jTable1.getValueAt(obtenerFila(), 0).toString(),
                    jTable1.getValueAt(obtenerFila(), 1).toString(),
                    jTable1.getValueAt(obtenerFila(), 2).toString(),
                    jTable1.getValueAt(obtenerFila(), 3).toString(),
                    jTable1.getValueAt(obtenerFila(), 4).toString(),
                    Double.parseDouble(jTable1.getValueAt(obtenerFila(), 5).toString()),
                    Double.parseDouble(jTable1.getValueAt(obtenerFila(), 6).toString()),
                    Double.parseDouble(jTable1.getValueAt(obtenerFila(), 7).toString()),
                    Double.parseDouble(jTable1.getValueAt(obtenerFila(), 8).toString()),
                    Integer.parseInt(jTable1.getValueAt(obtenerFila(), 9).toString()),
                    Integer.parseInt(jTable1.getValueAt(obtenerFila(), 10).toString()),
                    jTable1.getValueAt(obtenerFila(), 12).toString()));
            
            ep.setVisible(true);
            ep.setLocationRelativeTo(null);
        }

    }

      // Método para actualizar la tabla
    private void updateComponents(JTable tabla) {
        // Limpiar el modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);  // Esta es la forma correcta de limpiar la tabla

      mostrarProductos();

        // No es necesario llamar a removeAll() en JTable
        // Las siguientes líneas aseguran que la tabla se refresque correctamente
        tabla.setModel(modelo);
        tabla.revalidate();
        tabla.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agotados;
    private javax.swing.JLabel gananciasT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private com.mycompany.systemforreform.vista.PanelRound panelRound1;
    private com.mycompany.systemforreform.vista.PanelRound panelRound5;
    private com.mycompany.systemforreform.vista.PanelRound panelRound6;
    private com.mycompany.systemforreform.vista.PanelRound panelRound7;
    private com.mycompany.systemforreform.vista.PanelRound panelRound8;
    private javax.swing.JLabel totalP;
    private javax.swing.JLabel valorInventario;
    private javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables
}
