/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.systemforreform.vista.products;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.systemforreform.models.ProductosModel;

/**
 *
 * @author thevoid
 */
public class VistaProducto extends javax.swing.JFrame {

    private ProductosModel producto;

    public VistaProducto() {
        initComponents();
    }

    public VistaProducto(ProductosModel producto) {
        this();
        this.producto = producto;
        visialDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        descr = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        proveedor = new javax.swing.JTextField();
        description2 = new javax.swing.JLabel();
        description3 = new javax.swing.JLabel();
        description4 = new javax.swing.JLabel();
        description5 = new javax.swing.JLabel();
        description6 = new javax.swing.JLabel();
        description7 = new javax.swing.JLabel();
        description8 = new javax.swing.JLabel();
        description9 = new javax.swing.JLabel();
        precioC = new javax.swing.JTextField();
        precioV = new javax.swing.JTextField();
        ganancia = new javax.swing.JTextField();
        margen = new javax.swing.JTextField();
        stockI = new javax.swing.JTextField();
        stockM = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        categoria = new javax.swing.JTextField();
        description10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        nombre.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("jLabel1");

        id.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("jLabel1");

        descr.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        descr.setForeground(new java.awt.Color(255, 255, 255));
        descr.setText("jLabel1");

        description1.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description1.setForeground(new java.awt.Color(255, 255, 255));
        description1.setIcon(new FlatSVGIcon("product/van.svg"));
        description1.setText("Proveedor:");

        description2.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description2.setForeground(new java.awt.Color(255, 255, 255));
        description2.setIcon(new FlatSVGIcon("product/moneyP.svg"));
        description2.setText("Precios");

        description3.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description3.setForeground(new java.awt.Color(255, 255, 255));
        description3.setIcon(new FlatSVGIcon("product/compra.svg"));
        description3.setText("Compra:");

        description4.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description4.setForeground(new java.awt.Color(255, 255, 255));
        description4.setIcon(new FlatSVGIcon("product/sale.svg"));
        description4.setText("Venta:");

        description5.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description5.setForeground(new java.awt.Color(255, 255, 255));
        description5.setIcon(new FlatSVGIcon("product/gananci.svg"));
        description5.setText("Ganancia:");

        description6.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description6.setForeground(new java.awt.Color(255, 255, 255));
        description6.setIcon(new FlatSVGIcon("product/graph.svg"));
        description6.setText("Margen Bruto:");

        description7.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description7.setForeground(new java.awt.Color(255, 255, 255));
        description7.setIcon(new FlatSVGIcon("product/box1.svg"));
        description7.setText("Inventario");

        description8.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description8.setForeground(new java.awt.Color(255, 255, 255));
        description8.setIcon(new FlatSVGIcon("product/stockI.svg"));
        description8.setText("Stock Inicial:");

        description9.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description9.setForeground(new java.awt.Color(255, 255, 255));
        description9.setIcon(new FlatSVGIcon("product/stockM.svg"));
        description9.setText("Stock Minimo");

        jButton1.setIcon(new FlatSVGIcon("product/close.svg"));
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        description10.setFont(new java.awt.Font("ProFontWindows Nerd Font", 1, 14)); // NOI18N
        description10.setForeground(new java.awt.Color(255, 255, 255));
        description10.setIcon(new FlatSVGIcon("product/van.svg"));
        description10.setText("Categoría:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(description2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description8, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(description9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(description10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(precioC, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(proveedor)
                                    .addComponent(precioV)
                                    .addComponent(ganancia)
                                    .addComponent(margen)
                                    .addComponent(stockI)
                                    .addComponent(stockM)
                                    .addComponent(categoria))))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descr)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description1)
                    .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description10)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(description2)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description3)
                    .addComponent(precioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description4)
                    .addComponent(precioV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description5)
                    .addComponent(ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description6)
                    .addComponent(margen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(description7)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description8)
                    .addComponent(stockI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description9)
                    .addComponent(stockM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

     private void visialDatos(){
        nombre.setText(producto.getNombre());
        id.setText(producto.getIdProductos());
        descr.setText(producto.getDescripcion());
        categoria.setText(producto.getCategoria());
        proveedor.setText(producto.getProveedor());
        precioC.setText(String.valueOf(producto.getPrecioCompra()));
        precioV.setText(String.valueOf(producto.getPrecioVenta()));
        ganancia.setText(String.valueOf(producto.getGanancias()));
        margen.setText(String.valueOf(producto.getMargenBruto()));
        stockI.setText(String.valueOf(producto.getStockIncial()));
        stockM.setText(String.valueOf(producto.getStockMinimo()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoria;
    private javax.swing.JLabel descr;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description10;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel description3;
    private javax.swing.JLabel description4;
    private javax.swing.JLabel description5;
    private javax.swing.JLabel description6;
    private javax.swing.JLabel description7;
    private javax.swing.JLabel description8;
    private javax.swing.JLabel description9;
    private javax.swing.JTextField ganancia;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField margen;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField precioC;
    private javax.swing.JTextField precioV;
    private javax.swing.JTextField proveedor;
    private javax.swing.JTextField stockI;
    private javax.swing.JTextField stockM;
    // End of variables declaration//GEN-END:variables
}
